@startuml
skinparam classAttributeIconSize 0
!pragma layout smetana

class ViewLoader{
+newWindow(URL,String,Stage):void
+thisWindow(URL,ActionEvent):void
}

class FXMLLoader{
+load(URL):Parent
}

class Stage{
+setTitle(String):void
+setScene(Scene):void
+show():void
}

class Scene{}
class Parent{}

class MainController{
    #onNewCompany(ActionEvent):void
    #onNewCandidate(ActionEvent):void
    #onNewJobPost(ActionEvent):void
    #onQuit(ActionEvent):void
    #onCompaniesSection(ActionEvent):void
    #onCandidatesSection(ActionEvent):void
    #onJobPotsSection(ActionEvent):void
    #onEntityLink(ActionEvent):void
    #onEditButton(ActionEvent):void
    #onDeleteButton(ActionEvent):void
    #onSearchButton()
}

class CandidateProfileController{
#onBackButton():void
#onEditButton():void
}
class CandidateProfileEditController{
#onBackButton():void
#onSaveButton():void
}
class CompanyEditController{
#onBackButton():void
#onSaveButton():void
}
class CompanyNewController{
- agency:Agency
- nameField:TextField
- descriptionField:TextField
- addressField:TextField
- phoneField:TextField
+ CompanyNewController ()
+ onCancelButton(ActionEvent):void
+ onSaveButton(ActionEvent):void
}
class CompanyViewController{
#onBackButton():void
#onEditButton():void
}
class InterviewController {
#onCancelButton():void
#onOkButton():void
}
class JobPostController{
#onBackButton():void
#onEditButton():void
#onApplyButton():void
}



MainController --> ViewLoader
CandidateProfileController --> ViewLoader
CandidateProfileEditController --> ViewLoader
InterviewController --> ViewLoader
ViewLoader <-- JobPostController
ViewLoader <-- CompanyNewController
ViewLoader <-- CompanyEditController
CompanyViewController --> ViewLoader

ViewLoader --> FXMLLoader
ViewLoader --> Stage
ViewLoader --> Scene
ViewLoader --> Parent

@enduml