@startuml
skinparam classAttributeIconSize 0
!pragma layout smetana

class Model<<abstract>>{
    #id:String
    +Model(String)
    +getId():String
    +getType():String
    +setId(String):void
}

class Company extends Model{
    -name:String
    -address:String
    -phoneList:ArrayList<String>
    -sector:Branch
    -jobPostList:ArrayList<JobPost>
    +Company(String,String,String,String,Branch,ArrayList<JobPost>)
    +getName() :String
    +setName(String):void
    +getAddress():String
    +setAddress(String):void
    +getPhone():String
    +setPhone(String):void
    +getSector():Branch
    +setSector(Branch):void
    +getJobPostList():ArrayList<JobPost>
    +addJobPostToList(JobPost):void
    +setJobPostList(ArrayList<JobPost>):void
    +deleteNode():void
    -validatePhone(String):boolean
}
@enduml